CREATE TABLE WhyRomanData (
    id int(11) UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    user_uuid varchar(36) NOT NULL UNIQUE,
    app_time_ms int(11) UNSIGNED NOT NULL DEFAULT 0,
    max_andromeda_step TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    scales_selected JSON NOT NULL DEFAULT (JSON_ARRAY()),
    tour_restarted_count int(11) UNSIGNED NOT NULL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    INDEX(user_uuid)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
