name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint
        
      - name: Build
        run: npm run build

      - name: Start MySQL service
        run: sudo systemctl start mysql.service

          # - name: Create database
          #   run: |
          #     echo "CREATE DATABASE IF NOT EXISTS test" > setup.sql
          #     sudo mysql -h 127.0.0.1 -uroot -proot < setup.sql

      - name: Test
        env:
          TEST_DB_HOSTNAME: ${{ secrets.TEST_DB_HOSTNAME }}
          TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        run: npm run test

          # - name: Destroy test database
          #   run: |
          #     echo "DROP DATABASE test" > teardown.sql
          #     sudo mysql -h 127.0.0.1 -uroot -proot < teardown.sql
